steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-t'
      - '${_IMAGE_TAG}'
      - '.'

images:
  - '${_IMAGE_TAG}'

substitutions:
  _NEXT_PUBLIC_API_URL: 'http://localhost:8000'
  _IMAGE_TAG: 'placeholder'

timeout: '1200s'
